<?php
/**
 * YSRTech_DeeplTranslation_TranslateController
 *
 * Frontend controller for the Manual Translation AJAX endpoint.
 * Validates that an admin session is active before processing.
 *
 * Route: ysrtech_deepl/translate/run
 */
class YSRTech_DeeplTranslation_TranslateController extends Mage_Core_Controller_Front_Action
{
    public function runAction()
    {
        $response = $this->getResponse();
        $response->setHeader('Content-Type', 'application/json', true);

        // Ensure request is POST
        if (!$this->getRequest()->isPost()) {
            $response->setBody(Mage::helper('core')->jsonEncode(array(
                'output' => 'Error: invalid request method.',
            )));
            return;
        }

        // Validate one-time cache token generated by the admin block
        $token    = trim((string)$this->getRequest()->getPost('token'));
        $cacheKey = 'ysrtech_deepl_token_' . $token;
        if (!$token || !Mage::app()->getCache()->load($cacheKey)) {
            $response->setHttpResponseCode(403);
            $response->setBody(Mage::helper('core')->jsonEncode(array(
                'output' => 'Error: invalid or expired token. Please reload the configuration page.',
            )));
            return;
        }
        // Tokens are single-use; remove after validation
        Mage::app()->getCache()->remove($cacheKey);

        $storeCode = trim((string)$this->getRequest()->getPost('store_code'));
        $type      = trim((string)$this->getRequest()->getPost('type'));

        if (!$storeCode || !in_array($type, array('categories_all', 'categories_flagged', 'products_all', 'products_flagged'))) {
            $response->setBody(Mage::helper('core')->jsonEncode(array(
                'output' => 'Error: invalid parameters.',
            )));
            return;
        }

        $helper = Mage::helper('ysrtech_deepltranslation');
        if (!$helper->getApiKey()) {
            $response->setBody(Mage::helper('core')->jsonEncode(array(
                'output' => 'Error: no DeepL API key configured. Please save your API key first.',
            )));
            return;
        }

        // Verify destination store exists and is not the default
        try {
            $destStore    = Mage::app()->getStore($storeCode);
            $defaultStore = Mage::app()->getDefaultStoreView();
            if ($destStore->getId() == $defaultStore->getId()) {
                $response->setBody(Mage::helper('core')->jsonEncode(array(
                    'output' => 'Error: destination store cannot be the default store view.',
                )));
                return;
            }
        } catch (Mage_Core_Model_Store_Exception $e) {
            $response->setBody(Mage::helper('core')->jsonEncode(array(
                'output' => 'Error: store view "' . $storeCode . '" not found.',
            )));
            return;
        }

        set_time_limit(120);

        $sourceCode  = $defaultStore->getCode();
        $batchOffset = max(0, (int)$this->getRequest()->getPost('batch_offset'));

        ob_start();

        try {
            /** @var YSRTech_DeeplTranslation_Model_Translator $translator */
            $translator = Mage::getModel('ysrtech_deepltranslation/translator');
            $translator
                ->setStoreSource($sourceCode)
                ->setStoreDest($storeCode)
                ->setVerbose(true)
                ->setDebugMode(false)
                ->setDryRun(false)
                ->setBatchOffset($batchOffset);

            if ($type === 'categories_all') {
                $translator->setOnlyCategories(true)->setAllCategories(true);
            } elseif ($type === 'categories_flagged') {
                $translator->setOnlyCategories(true)->setAllCategories(false);
            } elseif ($type === 'products_all') {
                $translator->setOnlyProducts(true)->setAllProducts(true);
            } else {
                $translator->setOnlyProducts(true);
            }

            $translator->run();

        } catch (Exception $e) {
            echo 'Error: ' . $e->getMessage() . "\n";
            Mage::logException($e);
        }

        $output     = ob_get_clean();
        $nextOffset = isset($translator) ? $translator->getNextOffset() : null;

        // Issue a fresh token so the page can run again without a reload
        $newToken = md5(uniqid('ysrtech_deepl', true));
        Mage::app()->getCache()->save('1', 'ysrtech_deepl_token_' . $newToken, array(), 3600);

        $response->setBody(Mage::helper('core')->jsonEncode(array(
            'output'      => $output ?: 'Completed with no output.',
            'new_token'   => $newToken,
            'next_offset' => $nextOffset,
        )));
    }
}
